<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Welcome to Feather</title>
	<link rel="stylesheet" href="<?php echo Router::base_url(); ?>feather/stylesheets/screen.css">
</head>
<body>
	<div class="row">
		<h1>Welcome to Feather</h1>
		<h4>A custom lightweight PHP framework</h4>
	</div>
	<div class="row narrow">
		<p>This is the default page in Feather, which is generated by the default controller. The controller can be found in <code>app/controllers/example.php</code>, and the view can be found in <code>app/views/feather/default.php</code>.</p>
		<p>To change the default controller, change the <code>DEFAULT_CONTROLLER</code> setting in the <code>app/config.php</code> file.</p>
	</div>
</body>
</html>